[global]
device = Dev3
report_path = C:\Measurements

[channels]
;           phisical input, terminal config, scale name, max value (after scaling)
press1  = ai1, RSE, PressSens, 500, hPa
press2  = ai2, RSE, PressSens, 500, hPa
press3  = ai3, RSE, PressSens, 500, hPa
press4  = ai4, RSE, PressSens, 500, hPa
press5  = ai5, RSE, PressSens, 500, hPa

[fixed_lines]
line1 = 200
line2 = 500
