;[global]
;device = Dev3
;
;[channels]
;;           phisical input, terminal config, scale name, max value (after scaling)
;Pressure_2 = ai3, RSE, PressSens, 500, hPa
;Pressure_3 = ai2, RSE, PressSens, 500, hPa


[global]
device = Dev9

[channels]
;           phisical input, terminal config, scale name, max value (after scaling)
press1  = ai1, RSE, PressSens, 500, hPa
press9  = ai9, RSE, PressSens, 500, hPa
press2  = ai2, RSE, PressSens, 500, hPa
press10 = ai10, RSE, PressSens, 500, hPa
press3  = ai3, RSE, PressSens, 500, hPa
press11 = ai11, RSE, PressSens, 500, hPa
press4  = ai4, RSE, PressSens, 500, hPa
press12 = ai12, RSE, PressSens, 500, hPa
press5  = ai5, RSE, PressSens, 500, hPa
press13 = ai13, RSE, PressSens, 500, hPa
press6  = ai6, RSE, PressSens, 500, hPa

